version: "3.8"

services:
  workspace:
    build:
      context: .
      dockerfile: docker/workspace.Dockerfile
    volumes:
      - ./task_manager:/worksp
      - ./workspaces:/workspaces
    stdin_open: true
    tty: true

  test-runner:
    build:
      context: .
      dockerfile: docker/test_runner.Dockerfile
    volumes:
      - ./task_manager:/workspace
      - ./workspaces:/workspaces

  nginx-preview:
    build:
      context: .
      dockerfile: docker/nginx_preview.Dockerfile
    volumes:
      - ./preview:/usr/share/nginx/html
    ports:
      - "8080:80"
